<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HAT" failures="2" tests="6" name="TestTwo" time="0.053" errors="0" timestamp="2024-02-29T08:28:51 CST">
  <testcase classname="com.qa.testcases.testNg.RetryLogic" name="noRetryOnFailure" time="0.01">
    <skipped/>
  </testcase> <!-- noRetryOnFailure -->
  <testcase classname="com.qa.testcases.testNg.RetryLogic" name="retryOnFailure" time="0.009"/>
  <testcase classname="com.qa.testcases.testNg.RetryLogic" name="noRetryOnFailure" time="0.001">
    <skipped/>
  </testcase> <!-- noRetryOnFailure -->
  <testcase classname="com.qa.testcases.testNg.RetryLogic" name="noRetryOnFailure" time="0.0">
    <skipped/>
  </testcase> <!-- noRetryOnFailure -->
  <testcase classname="com.qa.testcases.testNg.RetryLogic" name="noRetryOnFailure" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.qa.testcases.testNg.RetryLogic.noRetryOnFailure(RetryLogic.java:18)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- noRetryOnFailure -->
  <testcase classname="com.qa.testcases.testNg.RetryLogic" name="noRetryOnFailure" time="0.033">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.testcases.testNg.TestNgBase.takeScreenshot(TestNgBase.java:125)
at com.qa.testcases.testNg.listner.MyTestListner.onTestFailure(MyTestListner.java:23)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- noRetryOnFailure -->
</testsuite> <!-- TestTwo -->
